# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: protocol/protocol.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class Request(betterproto.Message):
    set_tracker: "SetTrackerRequest" = betterproto.message_field(1, group="request")


@dataclass
class Response(betterproto.Message):
    set_tracker: "SetTrackerResponse" = betterproto.message_field(1, group="response")


@dataclass
class RldNodeMessage(betterproto.Message):
    id: str = betterproto.string_field(1)
    request: "Request" = betterproto.message_field(2, group="message")
    response: "Response" = betterproto.message_field(3, group="message")


@dataclass
class Position(betterproto.Message):
    x: int = betterproto.int32_field(1)
    y: int = betterproto.int32_field(2)


@dataclass
class Tracker(betterproto.Message):
    id: int = betterproto.int32_field(1)
    postion: "Position" = betterproto.message_field(2)


@dataclass
class SetTracker(betterproto.Message):
    request: "SetTrackerRequest" = betterproto.message_field(1, group="message")
    response: "SetTrackerResponse" = betterproto.message_field(2, group="message")
    error: str = betterproto.string_field(3, group="message")


@dataclass
class SetTrackerRequest(betterproto.Message):
    tracker: "Tracker" = betterproto.message_field(1)


@dataclass
class SetTrackerResponse(betterproto.Message):
    pass
